name: Central Keiba

on:
  schedule:
    - cron: "0 0 * * 6,0"     # 土曜(6), 日曜(0) の 09:00 JST (UTC 0:00)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: central-keiba
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Guard: run only Sat/Sun 09:00 JST (skip if scheduled)
        if: github.event_name == 'schedule'
        run: |
          HOUR_JST=$(date -u -d '+9 hours' +%H)
          DOW_JST=$(date -u -d '+9 hours' +%u)  # 1=Mon ... 7=Sun
          echo "Triggered by schedule. JST now: $(date -u -d '+9 hours' --iso-8601=seconds)"
          if [ "$DOW_JST" -ne 6 ] && [ "$DOW_JST" -ne 7 ]; then
            echo "Not weekend in JST. Skip."; exit 0; fi
          if [ "$HOUR_JST" != "09" ]; then
            echo "Not 09 JST. Skip."; exit 0; fi

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          # O1_MAX: "2.0"
          # GAP_MIN: "0.7"
          # HC_MAX: "12"
        run: python main.py